# More strict than package:lints/core.yaml
# See https://dart.dev/tools/analysis for details
include: package:lints/recommended.yaml

formatter:
  trailing_commas: preserve

linter:
  rules:
    package_api_docs: true
    public_member_api_docs: true
