name: aspose_barcode_cloud
description: This SDK allows you to work with Aspose.BarCode for Cloud REST APIs in your Dart or Flutter applications quickly and easily
version: 0.23.8+1
homepage: https://github.com/aspose-barcode-cloud/aspose-barcode-cloud-dart

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  http: '>=0.13.0 <2.0.0'
dev_dependencies:
  lints: ^2.1.1
  test: ^1.19.2
