name: "Dart test"

on:
  push:
    branches: [ v1 ]
  pull_request:
    branches: [ v1 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Dart test
        run: dart test
        env:
          TEST_CONFIGURATION_ACCESS_TOKEN: ${{ secrets.TEST_CONFIGURATION_ACCESS_TOKEN }}

      - name: Dart analyze
        run: dart analyze --fatal-infos lib example

      - name: Dart check format
        run: dart format --output=none --set-exit-if-changed .

      - name: Dart try publish
        run: dart pub publish --dry-run
