name: "Dart compile"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Dart compile
        run: dart compile js example/main.dart

      - name: Dart try publish
        run: dart pub publish --dry-run
